### ISSUE TITLE
Image(image, rectangle) is not type Image

### ISSUE THREAD

**Issue by comods** [RampantDespair/Aseprite-Library#1]
`Image(image, rectangle)` is not type `Image`. It may return `nil` so it is type `Image | nil`

`---@overload fun(otherImage: Image, rectangle: Rectangle): Image`
into
`---@overload fun(otherImage: Image, rectangle: Rectangle): Image | nil`

https://github.com/aseprite/aseprite/issues/4514

**Comment by comods** [comment]
https://github.com/RampantDespair/Aseprite-Library/pull/2

**Comment by comods** [comment]
I do not know if any of the others can return nil but I assume loading from file can return nil

**Comment by RampantDespair** [comment]
@RefinedSoftwareLLC 
#2 has been merged, thank you for contributing
